environment:
  matrix:
    - platform: x64

image: Visual Studio 2015

install:
  - ps: Install-Product node 8 x64
  - set CI=true
  - yarn --ignore-engines

build: off

matrix:
  fast_finish: true

shallow_clone: true

test_script:
  - node --version
  - yarn --version
  - yarn test-lint
  - yarn build-renderer
  - yarn build-app

# on_success:
#   - ps: Get-ChildItem .\dist\squirrel-windows\*.exe | % { Push-AppveyorArtifact $_.FullName }
